apiVersion: v1
kind: Service
metadata:
  labels:
    app: apple-website-clone-2021
    app.kubernetes.io/component: apple-website-clone-2021
    app.kubernetes.io/instance: apple-website-clone-2021
  name: apple-website-clone-2021
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    deployment: apple-website-clone-2021
  sessionAffinity: None
  type: ClusterIP
